{"Blinding Lights", "Pop", 5},
{"Shape of You", "Pop", 6},
{"Dance Monkey", "Pop", 9},
{"Uptown Funk", "Pop", 14},
{"Levitating", "Pop", 3},
{"Watermelon Sugar", "Pop", 18},
{"Happier Than Ever", "Pop", 22},
{"As It Was", "Pop", 12},
{"Peaches", "Pop", 30},
{"drivers license", "Pop", 10},

{"Bohemian Rhapsody", "Rock", 1},
{"Hotel California", "Rock", 4},
{"Stairway to Heaven", "Rock", 2},
{"Smells Like Teen Spirit", "Rock", 7},
{"Sweet Child O' Mine", "Rock", 15},
{"Back in Black", "Rock", 11},
{"Highway to Hell", "Rock", 19},
{"Imagine", "Rock", 8},
{"Wonderwall", "Rock", 20},
{"Livin' on a Prayer", "Rock", 24},

{"Lose Yourself", "Hip-Hop", 1},
{"God's Plan", "Hip-Hop", 13},
{"Sicko Mode", "Hip-Hop", 21},
{"HUMBLE.", "Hip-Hop", 17},
{"In Da Club", "Hip-Hop", 9},
{"Stronger", "Hip-Hop", 16},
{"Empire State of Mind", "Hip-Hop", 25},
{"Rockstar", "Hip-Hop", 31},
{"Old Town Road", "Hip-Hop", 29},
{"Lucid Dreams", "Hip-Hop", 32},

{"Take Five", "Jazz", 4},
{"So What", "Jazz", 1},
{"Feeling Good", "Jazz", 9},
{"My Favorite Things", "Jazz", 8},
{"What a Wonderful World", "Jazz", 3},
{"Blue in Green", "Jazz", 6},
{"Fly Me to the Moon", "Jazz", 2},
{"Autumn Leaves", "Jazz", 5},
{"All of Me", "Jazz", 10},
{"Cantaloupe Island", "Jazz", 7},

{"Weightless", "Ambient", 1},
{"An Ending (Ascent)", "Ambient", 2},
{"We Can Fly", "Ambient", 3},
{"Dreamscape", "Ambient", 4},
{"Calm Reflection", "Ambient", 5},
{"Into the Light", "Ambient", 6},
{"Soft Echoes", "Ambient", 7},
{"Slow Waves", "Ambient", 8},
{"Midnight Sky", "Ambient", 9},
{"Horizon Drift", "Ambient", 10},

{"Get Lucky", "Dance", 2},
{"Titanium", "Dance", 3},
{"Wake Me Up", "Dance", 5},
{"Don't You Worry Child", "Dance", 4},
{"Levels", "Dance", 1},
{"Animals", "Dance", 6},
{"Turn Down for What", "Dance", 8},
{"Tremor", "Dance", 7},
{"On the Floor", "Dance", 9},
{"Stay", "Dance", 10},

{"No Woman No Cry", "Reggae", 1},
{"Three Little Birds", "Reggae", 2},
{"One Love", "Reggae", 3},
{"Red Red Wine", "Reggae", 4},
{"Buffalo Soldier", "Reggae", 5},
{"Could You Be Loved", "Reggae", 6},
{"I Shot the Sheriff", "Reggae", 7},
{"Waiting in Vain", "Reggae", 8},
{"Sweat (A La La La La Long)", "Reggae", 9},
{"It Wasn't Me", "Reggae", 10},

{"Let Her Go", "Ballad", 1},
{"Someone Like You", "Ballad", 2},
{"Say Something", "Ballad", 3},
{"All of Me", "Ballad", 4},
{"Hello", "Ballad", 5},
{"Perfect", "Ballad", 6},
{"Photograph", "Ballad", 7},
{"When I Was Your Man", "Ballad", 8},
{"If I Ain’t Got You", "Ballad", 9},
{"Beneath Your Beautiful", "Ballad", 10},

{"I Will Wait", "Indie", 1},
{"Take Me to Church", "Indie", 2},
{"Sweater Weather", "Indie", 3},
{"Electric Feel", "Indie", 4},
{"Little Talks", "Indie", 5},
{"Stolen Dance", "Indie", 6},
{"Youth", "Indie", 7},
{"Riptide", "Indie", 8},
{"Dog Days Are Over", "Indie", 9},
{"Home", "Indie", 10}